---
- name: Using Play Scope Variables
  hosts: all
  vars:
   - a: tomcat8
   - b: present
   - c: no
  tasks:
   - name: Installing tomcat
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...  
