---
- name: Installing s/w using when conditions
  hosts: all
  vars:
   - a: 10
  tasks:
   - name: Installing maven
     apt:
      name: maven
      state: present
     when:
      a == 10
...     
           
