---
- name: creating user after checking user presence
  hosts: all
  tasks:
   - name: check user presence
     user:
      name: Harish
     register: a
   - name: display logs
     debug:
      var: a
   - name: create user
     user:
      name: Harish
      password: ravi080
     when:
      a.changed == false
...
